[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_LEGACY_BUILD_IMAGE = "false"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Netlify Identity Configuration
[context.production.environment]
  NETLIFY_IDENTITY_RECOVERY_URL = "https://magnaurbis.com/password-recovery.html"

[context.deploy-preview.environment]
  NETLIFY_IDENTITY_RECOVERY_URL = "https://magnaurbis.com/password-recovery.html"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https:; connect-src 'self' blob: https://*.netlify.com https://*.netlify.app;"